# Parameters that overwride the default or selected .sex file go here.

CATALOG_TYPE: 'ASCII_HEAD'    # Leave this here!
                              # All output catalogues are in HDF5 format.
VERBOSE_TYPE: 'QUIET'
FILTER_NAME: 'tophat_4.0_5x5.conv'
STARNNW_NAME: 'default.nnw'
---

# Define the desired output quantities here.
# Must give at least one.
 - X_IMAGE
 - Y_IMAGE
 - FLUX_AUTO
 - FLUXERR_AUTO
 - KRON_RADIUS
---

# Define uncertainty estimation parameters here.
# This is only compatible with FLUX_AUTO and FLUX_APER, when a weight image is given.
# Will overwrite the default uncertainty estimation for these fluxes.

# Will overide any CHECK_IMAGE settings to 'NONE'
# Will also include A_IMAGE, B_IMAGE, X_IMAGE, Y_IMAGE and KRON_RADIUS required for calculation in output catalogueue.


EMPIRICAL: True    # Whether to perform the empirical estimation.

 # The aperture radii to use for uncertainty estimation. [pixels]
RADII: [1.665,3.33172414,4.99844828,6.66517241,8.33189655,9.99862069,
11.66534483,13.33206897,14.9987931,16.66551724,18.33224138,19.99896552,
21.66568966,23.33241379,24.99913793,26.66586207,28.33258621,29.99931034,
31.66603448,33.33275862,34.99948276,36.6662069,38.33293103,39.99965517,
41.66637931,43.33310345,44.99982759,46.66655172,48.33327586,50]

D_SMALL: False    # The distance between apertures to enforce in the first iteration. [pixels]
                  # If False use the maximum diameter in this iteration.
D_LARGE: False      # The same but for the larger iteration. [pixels]

N_SMALL: 3000    # The number of apertures with radii below the median to use in the first iteration.
N_LARGE: 500    # The number of apertures with radii above the median to use in the second iteration.

WALKERS: 240    # Number of walkers to use in the MCMC.
ITER: 1024    # Number of MCMC iterations.
INITIAL: [1,1,1,1]    # Inital parameter guesses. 

SAVE_FIGS: True    # Save an images showing aperture locations and a plot of noise vs aperture size.
---

# Other parameters go here.

TO_FLUX: False   # Convert from counts to flux. False or conversion factor.

GET_WCS: True